### ISSUE TITLE
day-1-step-3 problems running app

### ISSUE THREAD

**Issue by martin-martin** [slash4-de/django#49]
Hei - thanks for the great tutorial! : )
I've come across this error when trying to run the app:

```sh
martinmartin:~/workspace (day-1-step-3) $ git checkout -f day-1-step-3
Already on 'day-1-step-3'
Your branch is up-to-date with 'origin/day-1-step-3'.
martinmartin:~/workspace (day-1-step-3) $ ./manage.py runserver $IP:$PORT
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x7fec09e20668>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ubuntu/workspace/myevent/urls.py", line 21, in <module>
    url(r'^$', 'events.views.home', name='home'),
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 85, in url
    raise TypeError('view must be a callable or a list/tuple in the case of include().')
TypeError: view must be a callable or a list/tuple in the case of include().
```

I tried resetting the repo to the `day-1-step-3` branch (even though I didn't do any changes) and tried running the server again.

Not sure this is an error or whether I'm doing something wrong, but since the repo is reset to its original state, I thought maybe it's useful if I notify you about this.

**Comment by martin-martin** [comment]
I get the same error when trying to run the app also in further sections (branches) of the project.

I managed to get it to display the same page as in the tutorial on `day-1-step-1`, however only after following the instructions on the error page and adding my app's URL to the `ALLOWED_HOSTS = []` lists in `myevent/myevent/settings.py`.
